"""
dashboard.py  ·  LoRRI — AI Route Intelligence Platform
========================================================
Run: streamlit run dashboard.py
Requires: shipments.csv  routes.csv  metrics.csv  vehicle_summary.csv
          (generated by: python generate_data.py && python route_solver.py)
"""

import time
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from math import radians, cos, sin, asin, sqrt

# ══════════════════════════════════════════════════════════════════════════════
# CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════
DEPOT = {"id": "DEPOT", "city": "Mumbai", "latitude": 19.0760, "longitude": 72.8777}
VEHICLE_CAP    = 800
AVG_SPEED      = 55

VEHICLE_COLORS = ["#00D4FF","#F59E0B","#A78BFA","#10B981","#F97316","#EC4899","#34D399","#FBBF24"]
PRIORITY_COLORS = {"HIGH": "#FF4D4D", "MEDIUM": "#F59E0B", "LOW": "#10B981"}

PLOTLY_BASE = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="'IBM Plex Mono','Courier New',monospace", color="#64748B", size=11),
    margin=dict(l=12, r=12, t=38, b=12),
    xaxis=dict(gridcolor="rgba(255,255,255,0.04)", linecolor="rgba(255,255,255,0.07)",
               tickfont=dict(size=10)),
    yaxis=dict(gridcolor="rgba(255,255,255,0.04)", linecolor="rgba(255,255,255,0.07)",
               tickfont=dict(size=10)),
    legend=dict(bgcolor="rgba(10,15,20,0.92)", bordercolor="rgba(255,255,255,0.07)",
                borderwidth=1, font=dict(size=10)),
    hoverlabel=dict(bgcolor="#131A22", bordercolor="rgba(0,212,255,0.4)",
                    font=dict(family="'IBM Plex Mono',monospace", size=11, color="#E8EEF4")),
)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE CONFIG
# ══════════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="LoRRI · AI Route Intelligence",
    layout="wide", page_icon="🚚",
    initial_sidebar_state="expanded",
)

# ══════════════════════════════════════════════════════════════════════════════
# GLOBAL CSS — Industrial command-center aesthetic
# Fonts: IBM Plex Mono (data) + Barlow Condensed (headers) + Barlow (body)
# Color story: #070B0F base · #00D4FF cyan accent · #F59E0B amber · #10B981 green
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600;700&family=Barlow:wght@300;400;500;600;700&family=Barlow+Condensed:wght@400;500;600;700;800&display=swap');

:root {
    --bg:        #070B0F;
    --surface:   #0D1117;
    --elevated:  #131A22;
    --card:      #161E28;
    --border:    rgba(255,255,255,0.07);
    --border-hi: rgba(255,255,255,0.13);
    --accent:    #00D4FF;
    --a-dim:     rgba(0,212,255,0.10);
    --a-mid:     rgba(0,212,255,0.22);
    --amber:     #F59E0B;
    --am-dim:    rgba(245,158,11,0.10);
    --green:     #10B981;
    --gr-dim:    rgba(16,185,129,0.10);
    --red:       #FF4D4D;
    --rd-dim:    rgba(255,77,77,0.10);
    --violet:    #8B5CF6;
    --t1:        #E8EEF4;
    --t2:        #94A3B8;
    --t3:        #475569;
    --t4:        #1E293B;
    --fd:        'Barlow Condensed',sans-serif;
    --fb:        'Barlow',sans-serif;
    --fm:        'IBM Plex Mono','Courier New',monospace;
}

html,body,[class*="css"]{font-family:var(--fb)!important;background:var(--bg)!important;color:var(--t1)!important;}
.stApp{background:var(--bg)!important;}
.main .block-container{padding:0 1.5rem 2rem!important;max-width:100%!important;}
h1,h2,h3{font-family:var(--fd)!important;letter-spacing:0.02em!important;}
hr{border:none!important;border-top:1px solid var(--border)!important;margin:.8rem 0!important;}

/* ── SIDEBAR ── */
[data-testid="stSidebar"]{
    background:linear-gradient(180deg,#060A0E 0%,#080C10 100%)!important;
    border-right:1px solid rgba(0,212,255,0.08)!important;
}
[data-testid="stSidebar"] *{color:var(--t1)!important;}
[data-testid="stSidebar"] .stMultiSelect label,
[data-testid="stSidebar"] .stSelectbox label,
[data-testid="stSidebar"] .stSlider label,
[data-testid="stSidebar"] .stToggle label{
    font-family:var(--fm)!important;font-size:.62rem!important;font-weight:500!important;
    letter-spacing:.14em!important;text-transform:uppercase!important;color:var(--t3)!important;
}
[data-testid="stSidebar"] [data-baseweb="tag"]{
    background:var(--a-dim)!important;border:1px solid var(--a-mid)!important;border-radius:4px!important;
}
[data-testid="stSidebar"] [data-baseweb="tag"] span{font-family:var(--fm)!important;font-size:.7rem!important;color:var(--accent)!important;}
[data-testid="stSidebar"] [data-baseweb="select"]>div{
    background:rgba(255,255,255,.03)!important;border-color:rgba(255,255,255,.09)!important;border-radius:6px!important;
}
[data-testid="stSidebar"] .stButton>button{
    width:100%!important;font-family:var(--fm)!important;font-size:.7rem!important;
    font-weight:600!important;letter-spacing:.1em!important;text-transform:uppercase!important;
    border-radius:6px!important;padding:10px 14px!important;transition:all .15s!important;
}
[data-testid="stSidebar"] .stButton>button[kind="primary"]{
    background:linear-gradient(135deg,#00B4D8,#0077B6)!important;
    border:1px solid rgba(0,212,255,.35)!important;color:#fff!important;
    box-shadow:0 0 16px rgba(0,212,255,.18)!important;
}
[data-testid="stSidebar"] .stButton>button[kind="primary"]:hover{
    box-shadow:0 0 28px rgba(0,212,255,.35)!important;transform:translateY(-1px)!important;
}
[data-testid="stSidebar"] .stButton>button:not([kind="primary"]){
    background:rgba(255,255,255,.03)!important;border:1px solid rgba(255,255,255,.09)!important;color:var(--t2)!important;
}

/* ── METRICS ── */
[data-testid="metric-container"]{
    background:var(--card)!important;border:1px solid var(--border)!important;border-radius:10px!important;padding:14px 16px 12px!important;
}
[data-testid="metric-container"] label{
    font-family:var(--fm)!important;font-size:.58rem!important;font-weight:500!important;
    letter-spacing:.14em!important;text-transform:uppercase!important;color:var(--t3)!important;
}
[data-testid="metric-container"] [data-testid="stMetricValue"]{
    font-family:var(--fm)!important;font-size:1.3rem!important;font-weight:700!important;color:var(--t1)!important;
}
[data-testid="metric-container"] [data-testid="stMetricDelta"]{font-family:var(--fm)!important;font-size:.7rem!important;}

/* ── TABS ── */
[data-baseweb="tab-list"]{
    background:var(--elevated)!important;border:1px solid var(--border)!important;
    border-radius:10px!important;gap:2px!important;padding:4px!important;
}
[data-baseweb="tab"]{
    border-radius:6px!important;font-family:var(--fm)!important;font-size:.7rem!important;
    font-weight:500!important;letter-spacing:.06em!important;color:var(--t2)!important;padding:8px 14px!important;
}
[aria-selected="true"][data-baseweb="tab"]{background:var(--a-dim)!important;color:var(--accent)!important;border:1px solid var(--a-mid)!important;}
[data-baseweb="tab-highlight"]{display:none!important;}

/* ── DATAFRAME ── */
[data-testid="stDataFrame"]{border:1px solid var(--border)!important;border-radius:10px!important;overflow:hidden!important;}

/* ── CHAT ── */
[data-testid="stChatInput"]{background:var(--elevated)!important;border:1px solid rgba(0,212,255,.15)!important;border-radius:10px!important;}
[data-testid="stChatInput"] textarea{font-family:var(--fb)!important;color:var(--t1)!important;background:transparent!important;}
[data-testid="stChatMessage"]{background:var(--elevated)!important;border:1px solid var(--border)!important;border-radius:10px!important;}

/* ── BUTTONS ── */
.stButton>button{font-family:var(--fb)!important;font-weight:600!important;border-radius:6px!important;transition:all .15s!important;}
.stButton>button[kind="primary"]{background:linear-gradient(135deg,#0096B7,#005F73)!important;border:1px solid var(--a-mid)!important;color:#fff!important;}
.stButton>button[kind="primary"]:hover{box-shadow:0 0 20px rgba(0,212,255,.22)!important;transform:translateY(-1px)!important;}
.stButton>button:not([kind="primary"]){background:var(--elevated)!important;border:1px solid var(--border)!important;color:var(--t2)!important;}
.stButton>button:not([kind="primary"]):hover{border-color:rgba(0,212,255,.28)!important;color:var(--accent)!important;}

/* ── CAPTION ── */
.stCaption,[data-testid="stCaptionContainer"]{font-family:var(--fm)!important;font-size:.66rem!important;color:var(--t3)!important;letter-spacing:.05em!important;}

/* ════ COMPONENTS ═════════════════════════════════════ */

/* Page header */
.ph{background:linear-gradient(135deg,rgba(0,212,255,.05) 0%,rgba(13,17,23,.4) 50%,rgba(245,158,11,.03) 100%);
    border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:18px 22px;margin-bottom:16px;position:relative;overflow:hidden;}
.ph::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;
    background:linear-gradient(90deg,transparent 0%,rgba(0,212,255,.6) 30%,rgba(245,158,11,.4) 70%,transparent 100%);}
.ph-title{font-family:var(--fd);font-size:1.75rem;font-weight:800;letter-spacing:.05em;color:var(--t1);line-height:1.1;}
.ph-title span{color:var(--accent);}
.ph-sub{font-family:var(--fm);font-size:.64rem;color:var(--t3);letter-spacing:.1em;margin-top:5px;}
.ph-badge{text-align:center;padding:10px 14px;border-radius:8px;min-width:72px;}

/* KPI card */
.kc{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:14px 16px;position:relative;overflow:hidden;height:100%;}
.kc::after{content:'';position:absolute;bottom:0;left:0;width:100%;height:2px;border-radius:0 0 10px 10px;}
.kc.cy::after{background:linear-gradient(90deg,var(--accent),transparent);}
.kc.am::after{background:linear-gradient(90deg,var(--amber),transparent);}
.kc.gr::after{background:linear-gradient(90deg,var(--green),transparent);}
.kc.vi::after{background:linear-gradient(90deg,var(--violet),transparent);}
.kc-lbl{font-family:var(--fm);font-size:.58rem;font-weight:500;letter-spacing:.18em;text-transform:uppercase;color:var(--t3);margin-bottom:6px;}
.kc-val{font-family:var(--fm);font-size:1.45rem;font-weight:700;color:var(--t1);line-height:1.1;}
.kc-d{font-family:var(--fm);font-size:.66rem;font-weight:500;margin-top:4px;}
.kc-d.up{color:var(--green);} .kc-d.neu{color:var(--accent);}

/* Section header */
.sh{display:flex;align-items:center;gap:10px;margin:18px 0 12px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,.05);}
.sh-icon{width:28px;height:28px;background:var(--a-dim);border:1px solid var(--a-mid);border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:.85rem;flex-shrink:0;}
.sh-title{font-family:var(--fd);font-size:1.0rem;font-weight:700;color:var(--t1);letter-spacing:.04em;}
.sh-badge{margin-left:auto;border-radius:999px;padding:2px 9px;font-family:var(--fm);font-size:.56rem;font-weight:600;letter-spacing:.14em;text-transform:uppercase;}
.sh-badge.cy{background:var(--a-dim);color:var(--accent);border:1px solid var(--a-mid);}
.sh-badge.gr{background:var(--gr-dim);color:var(--green);border:1px solid rgba(16,185,129,.25);}
.sh-badge.am{background:var(--am-dim);color:var(--amber);border:1px solid rgba(245,158,11,.25);}
.sh-badge.rd{background:var(--rd-dim);color:var(--red);border:1px solid rgba(255,77,77,.25);}

/* Info boxes */
.bx{border-radius:0 6px 6px 0;padding:10px 14px;margin:8px 0 12px;font-family:var(--fb);font-size:.83rem;line-height:1.65;color:var(--t2);}
.bx.i{background:var(--a-dim);border-left:2px solid var(--accent);}
.bx.w{background:var(--am-dim);border-left:2px solid var(--amber);}
.bx.o{background:var(--gr-dim);border-left:2px solid var(--green);}
.bx.e{background:var(--rd-dim);border-left:2px solid var(--red);}

/* Sidebar brand */
.sbb{background:linear-gradient(135deg,rgba(0,212,255,.08) 0%,rgba(0,0,0,0) 60%);
    border-bottom:1px solid rgba(0,212,255,.1);padding:20px 16px 16px;margin-bottom:4px;}
.sbb-name{font-family:var(--fd);font-size:1.85rem;font-weight:800;letter-spacing:.1em;color:var(--t1);line-height:1;}
.sbb-sub{font-family:var(--fm);font-size:.56rem;color:var(--t3);letter-spacing:.18em;text-transform:uppercase;margin-top:3px;}
.sbb-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--green);
    box-shadow:0 0 8px var(--green);margin-right:5px;vertical-align:middle;}

/* Sidebar section label */
.sbs{font-family:var(--fm);font-size:.56rem;font-weight:600;letter-spacing:.22em;text-transform:uppercase;
    color:rgba(0,212,255,.6);padding:13px 16px 5px;border-top:1px solid rgba(255,255,255,.05);}

/* Sidebar stat */
.sst{display:flex;justify-content:space-between;align-items:center;padding:6px 10px;
    background:rgba(255,255,255,.02);border-radius:5px;margin:3px 0;border:1px solid rgba(255,255,255,.04);}
.sst-l{font-family:var(--fm);font-size:.63rem;color:var(--t3);}
.sst-v{font-family:var(--fm);font-size:.74rem;font-weight:600;color:var(--t1);}

/* Map container */
.mc{border:1px solid rgba(0,212,255,.1);border-radius:14px;overflow:hidden;
    box-shadow:0 0 40px rgba(0,0,0,.5),inset 0 0 0 1px rgba(255,255,255,.03);}

/* Vehicle pill */
.vp{display:inline-flex;align-items:center;gap:5px;background:rgba(255,255,255,.03);
    border:1px solid rgba(255,255,255,.07);border-radius:999px;padding:3px 9px 3px 6px;
    margin:2px;font-family:var(--fm);font-size:.67rem;font-weight:500;color:var(--t2);}
.vd{width:7px;height:7px;border-radius:50%;flex-shrink:0;}

/* Sim idle */
.si{text-align:center;padding:36px 20px;border:1px dashed rgba(255,255,255,.07);border-radius:12px;}
.si-i{font-size:2rem;margin-bottom:8px;}
.si-t{font-family:var(--fd);font-size:.95rem;font-weight:700;color:var(--t2);margin-bottom:4px;}
.si-s{font-family:var(--fm);font-size:.67rem;color:var(--t3);}

/* Chat empty */
.ce{text-align:center;padding:36px 20px;border:1px dashed rgba(255,255,255,.07);border-radius:12px;margin-bottom:14px;}
.ce-i{font-size:1.8rem;margin-bottom:8px;}
.ce-t{font-family:var(--fd);font-size:.95rem;font-weight:700;color:var(--t2);margin-bottom:4px;}
.ce-s{font-family:var(--fm);font-size:.67rem;color:var(--t3);}

/* Table label */
.tbl-lbl{font-family:'Barlow Condensed',sans-serif;font-size:.82rem;font-weight:700;
    color:var(--t2);letter-spacing:.07em;margin:8px 0 4px;}

/* Footer */
.footer{text-align:center;padding:14px 0 6px;border-top:1px solid rgba(255,255,255,.04);
    margin-top:28px;font-family:var(--fm);font-size:.6rem;color:var(--t4);letter-spacing:.1em;}
</style>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════════════
def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    a = sin((lat2-lat1)/2)**2 + cos(lat1)*cos(lat2)*sin((lon2-lon1)/2)**2
    return 2 * R * asin(sqrt(a))


def chart(fig, height=300, title=""):
    layout = dict(**PLOTLY_BASE, height=height)
    if title:
        layout["title"] = dict(
            text=title,
            font=dict(family="'Barlow Condensed',sans-serif", size=12, color="#94A3B8"),
            x=0, xref="paper", pad=dict(l=0, t=2),
        )
    fig.update_layout(**layout)
    return fig


def box(content, kind="i"):
    st.markdown(f'<div class="bx {kind}">{content}</div>', unsafe_allow_html=True)


def sec(icon, title, badge="", badge_class="cy"):
    b = f'<span class="sh-badge {badge_class}">{badge}</span>' if badge else ""
    st.markdown(f"""
    <div class="sh">
        <div class="sh-icon">{icon}</div>
        <span class="sh-title">{title}</span>
        {b}
    </div>""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# DATA LOADING & ANALYTICS
# ══════════════════════════════════════════════════════════════════════════════
@st.cache_data
def load_data():
    ships   = pd.read_csv("shipments.csv")
    routes  = pd.read_csv("routes.csv")
    metrics = pd.read_csv("metrics.csv").iloc[0]
    veh     = pd.read_csv("vehicle_summary.csv")
    return ships, routes, metrics, veh


@st.cache_data
def calc_feature_importance(routes_df):
    np.random.seed(42)
    features = {
        "Travel Time":    "travel_time_hr",
        "Fuel Cost":      "fuel_cost",
        "Toll Cost":      "toll_cost",
        "Driver Cost":    "driver_cost",
        "Carbon Emitted": "carbon_kg",
        "SLA Breach":     "sla_breach_hr",
        "Package Weight": "weight",
    }
    X = routes_df[list(features.values())].copy()
    y = routes_df["mo_score"].values
    base_mae = np.mean(np.abs(y - y.mean()))
    scores = {}
    for label, col in features.items():
        Xs = X.copy(); Xs[col] = np.random.permutation(Xs[col].values)
        proxy = Xs.apply(lambda c: (c - c.mean()) / (c.std() + 1e-9)).mean(axis=1)
        scores[label] = abs(np.mean(np.abs(y - proxy.values)) - base_mae)
    total = sum(scores.values()) + 1e-9
    return {k: round(v/total*100, 1) for k, v in sorted(scores.items(), key=lambda x: -x[1])}


@st.cache_data
def calc_stop_contributions(routes_df):
    cols    = ["travel_time_hr","fuel_cost","toll_cost","driver_cost","carbon_kg","sla_breach_hr"]
    labels  = ["Travel Time","Fuel Cost","Toll Cost","Driver Cost","Carbon","SLA Breach"]
    wts     = [0.30, 0.20, 0.05, 0.15, 0.20, 0.10]
    df = routes_df[cols].copy()
    for c in cols:
        rng = df[c].max() - df[c].min()
        df[c] = (df[c] - df[c].min()) / (rng + 1e-9)
    for i, c in enumerate(cols):
        df[c] = df[c] * wts[i]
    df.columns = labels
    df["city"]     = routes_df["city"].values
    df["vehicle"]  = routes_df["vehicle"].values
    df["mo_score"] = routes_df["mo_score"].values
    return df


@st.cache_data
def build_rag_context(routes_df, metrics_s, veh_df, ships_df):
    m = metrics_s
    top_cost    = routes_df.nlargest(5,"total_cost")[["city","vehicle","priority","total_cost","carbon_kg","sla_breach_hr"]].to_string(index=False)
    br          = routes_df[routes_df["sla_breach_hr"]>0][["city","vehicle","priority","sla_breach_hr"]]
    breach_str  = br.to_string(index=False) if not br.empty else "NONE — all deliveries within SLA"
    top_traffic = ships_df.nlargest(5,"traffic_mult")[["city","traffic_mult","priority","sla_hours"]].to_string(index=False)
    top_veh     = veh_df.sort_values("distance_km", ascending=False).iloc[0]
    return f"""You are LoRRI Copilot, an expert AI logistics analyst. You have live access to this optimization run.
Answer concisely with exact data. Use ₹ for rupees. Use bullet lists for multi-item answers.

[CONFIG]
  Depot: Mumbai | Shipments: {int(m['num_shipments'])} | Vehicles: {int(m['num_vehicles'])} | Cap: 800kg
  Weights: Cost 35% | Time 30% | Carbon 20% | SLA 15%

[BASELINE vs OPTIMIZED]
  Distance : {m['baseline_distance_km']:.1f}km → {m['opt_distance_km']:.1f}km (saved {m['baseline_distance_km']-m['opt_distance_km']:.1f}km, -{(m['baseline_distance_km']-m['opt_distance_km'])/m['baseline_distance_km']*100:.1f}%)
  Time     : {m['baseline_time_hr']:.1f}hr → {m['opt_time_hr']:.1f}hr
  Fuel     : ₹{m['baseline_fuel_cost']:,.0f} → ₹{m['opt_fuel_cost']:,.0f} (saved ₹{m['baseline_fuel_cost']-m['opt_fuel_cost']:,.0f})
  Toll     : ₹{m['baseline_toll_cost']:,.0f} → ₹{m['opt_toll_cost']:,.0f}
  Driver   : ₹{m['baseline_driver_cost']:,.0f} → ₹{m['opt_driver_cost']:,.0f}
  Total    : ₹{m['baseline_total_cost']:,.0f} → ₹{m['opt_total_cost']:,.0f} (saved ₹{m['baseline_total_cost']-m['opt_total_cost']:,.0f}, -{(m['baseline_total_cost']-m['opt_total_cost'])/m['baseline_total_cost']*100:.1f}%)
  Carbon   : {m['baseline_carbon_kg']:.1f}kg → {m['opt_carbon_kg']:.1f}kg (saved {m['baseline_carbon_kg']-m['opt_carbon_kg']:.1f}kg)
  SLA      : {m['baseline_sla_adherence_pct']:.1f}% → {m['opt_sla_adherence_pct']:.1f}%

[LONGEST ROUTE VEHICLE]
  V{int(top_veh['vehicle'])} · {top_veh['distance_km']:.1f}km · {top_veh['stops']} stops · util {top_veh['utilization_pct']:.1f}% · ₹{top_veh['total_cost']:,.0f}

[ALL VEHICLES]
{veh_df.to_string(index=False)}

[TOP 5 HIGHEST-COST DELIVERIES]
{top_cost}

[SLA BREACHES]
{breach_str}

[TOP TRAFFIC CITIES]
{top_traffic}"""


# ── Simulation helpers ────────────────────────────────────────────────────────
def sim_traffic(city, new_mult, ships_df, routes_df):
    row       = ships_df[ships_df["city"] == city].iloc[0]
    orig_mult = float(row["traffic_mult"])
    d         = haversine(DEPOT["latitude"], DEPOT["longitude"], float(row["latitude"]), float(row["longitude"]))
    orig_t    = d / (AVG_SPEED / orig_mult)
    new_t     = d / (AVG_SPEED / new_mult)
    pct       = (new_t - orig_t) / orig_t * 100
    res       = {"city": city, "orig_mult": orig_mult, "new_mult": new_mult,
                 "pct": round(pct, 1), "triggered": pct > 30, "dist_km": round(d, 1)}
    if res["triggered"]:
        aff = routes_df[routes_df["city"] == city]["vehicle"].values
        if len(aff):
            vid = int(aff[0])
            orig = routes_df[routes_df["vehicle"] == vid].sort_values("stop_order").copy()
            mask = orig["city"] == city
            reopt = pd.concat([orig[~mask], orig[mask]]).reset_index(drop=True)
            def rdist(df):
                pts = [DEPOT] + df.to_dict("records") + [DEPOT]
                return round(sum(haversine(pts[i]["latitude"],pts[i]["longitude"],pts[i+1]["latitude"],pts[i+1]["longitude"]) for i in range(len(pts)-1)), 1)
            res.update({"vid": vid, "orig": orig, "reopt": reopt,
                        "od": rdist(orig), "nd": rdist(reopt)})
    return res


def sim_escalate(city, ships_df, routes_df):
    row  = ships_df[ships_df["city"] == city].iloc[0]
    op   = str(row["priority"]); os = int(row["sla_hours"])
    if op == "HIGH":
        return {"already": True, "city": city}
    aff  = routes_df[routes_df["city"] == city]["vehicle"].values
    vid  = int(aff[0]) if len(aff) else 1
    orig = routes_df[routes_df["vehicle"] == vid].sort_values("stop_order").copy()
    mask = orig["city"] == city
    new  = pd.concat([orig[mask], orig[~mask]]).reset_index(drop=True)
    ot   = round(float(orig["travel_time_hr"].sum()), 1)
    return {"already": False, "city": city, "op": op, "os": os,
            "vid": vid, "orig": orig, "new": new, "ot": ot, "nt": round(ot*0.88, 1)}


ships, routes, metrics, veh_summary = load_data()
fi  = calc_feature_importance(routes)
sc  = calc_stop_contributions(routes)
rag = build_rag_context(routes, metrics, veh_summary, ships)
all_v = sorted(routes["vehicle"].unique().tolist())
all_p = ["HIGH", "MEDIUM", "LOW"]


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR — OPERATIONS PANEL
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("""
    <div class="sbb">
        <div class="sbb-name">LoRRI</div>
        <div class="sbb-sub">AI Route Intelligence Platform</div>
        <div style="margin-top:10px;display:flex;align-items:center;">
            <span class="sbb-dot"></span>
            <span style="font-family:var(--fm);font-size:.62rem;color:#10B981;letter-spacing:.1em;">SYSTEM ONLINE</span>
            <span style="font-family:var(--fm);font-size:.58rem;color:#334155;margin-left:6px;">· MUMBAI DEPOT</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Fleet Filters
    st.markdown('<div class="sbs">🚛  FLEET FILTERS</div>', unsafe_allow_html=True)
    sel_v = st.multiselect("Active Vehicles", all_v, default=all_v, format_func=lambda v: f"Vehicle {v}")
    sel_p = st.multiselect("Delivery Priority", all_p, default=all_p)

    # Map Display
    st.markdown('<div class="sbs">🗺️  MAP DISPLAY</div>', unsafe_allow_html=True)
    show_baseline   = st.toggle("Overlay Baseline Route", value=False)
    show_unassigned = st.toggle("Show Unassigned Stops",  value=True)

    # Simulation Controls
    st.markdown('<div class="sbs">⚡  SIMULATION CONTROLS</div>', unsafe_allow_html=True)
    sim_mode = st.selectbox("Disruption Type", ["— None —","🚦 Traffic Jam","🚨 Priority Escalation"])

    if sim_mode == "🚦 Traffic Jam":
        sim_city = st.selectbox("Affected City", sorted(ships["city"].tolist()), key="sc_t")
        sim_mult = st.slider("Traffic Multiplier", 1.0, 3.0, 2.5, 0.1, help="1.0=clear · 3.0=gridlock")
        if st.button("🔴  Trigger Re-Optimization", type="primary"):
            with st.spinner("Analysing disruption…"):
                time.sleep(0.6)
                st.session_state["sim_r"] = ("traffic", sim_traffic(sim_city, sim_mult, ships, routes))

    elif sim_mode == "🚨 Priority Escalation":
        esc_city = st.selectbox("Escalate Shipment", sorted(ships["city"].tolist()), key="sc_e")
        if st.button("🚨  Escalate to HIGH Priority", type="primary"):
            with st.spinner("Re-routing vehicle…"):
                time.sleep(0.6)
                st.session_state["sim_r"] = ("esc", sim_escalate(esc_city, ships, routes))
    else:
        st.session_state.pop("sim_r", None)

    if st.session_state.get("sim_r") and sim_mode != "— None —":
        if st.button("✕  Clear Result"):
            st.session_state.pop("sim_r", None); st.rerun()

    # Fleet Snapshot
    st.markdown('<div class="sbs">📊  FLEET SNAPSHOT</div>', unsafe_allow_html=True)
    av = sel_v or all_v; ap = sel_p or all_p
    fr = routes[routes["vehicle"].isin(av) & routes["priority"].isin(ap)]
    avg_u = veh_summary[veh_summary["vehicle"].isin(av)]["utilization_pct"].mean() if av else 0
    nb = fr[fr["sla_breach_hr"]>0].shape[0]
    st.markdown(f"""
    <div class="sst"><span class="sst-l">Active Stops</span><span class="sst-v">{len(fr)}</span></div>
    <div class="sst"><span class="sst-l">Fleet CO₂</span><span class="sst-v" style="color:#8B5CF6">{fr['carbon_kg'].sum():.0f} kg</span></div>
    <div class="sst"><span class="sst-l">Route Cost</span><span class="sst-v" style="color:#F59E0B">₹{fr['total_cost'].sum():,.0f}</span></div>
    <div class="sst"><span class="sst-l">Avg Utilisation</span><span class="sst-v" style="color:{'#10B981' if avg_u>=55 else '#F59E0B'}">{avg_u:.1f}%</span></div>
    <div class="sst"><span class="sst-l">SLA Breaches</span><span class="sst-v" style="color:{'#FF4D4D' if nb>0 else '#10B981'}">{nb}</span></div>
    """, unsafe_allow_html=True)

    # Vehicle Legend
    st.markdown('<div class="sbs">🎨  VEHICLE LEGEND</div>', unsafe_allow_html=True)
    pills = "".join(
        f'<span class="vp"><span class="vd" style="background:{VEHICLE_COLORS[(v-1)%len(VEHICLE_COLORS)]}"></span>'
        f'V{v} · {len(routes[routes["vehicle"]==v])} stops</span>'
        for v in all_v
    )
    st.markdown(f'<div style="padding:4px 0">{pills}</div>', unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# MAIN — resolved filter values
# ══════════════════════════════════════════════════════════════════════════════
av = sel_v or all_v
ap = sel_p or all_p

# ── Page Header ───────────────────────────────────────────────────────────────
cp  = (metrics['baseline_total_cost'] -metrics['opt_total_cost'])  / metrics['baseline_total_cost'] *100
crp = (metrics['baseline_carbon_kg']  -metrics['opt_carbon_kg'])   / metrics['baseline_carbon_kg']  *100
dp  = (metrics['baseline_distance_km']-metrics['opt_distance_km']) / metrics['baseline_distance_km']*100

st.markdown(f"""
<div class="ph">
  <div style="display:flex;align-items:center;gap:16px;">
    <div style="flex:1">
      <div class="ph-title">Lo<span>RRI</span>
        <span style="font-size:1rem;font-weight:400;color:#475569;letter-spacing:.02em"> · AI Route Intelligence Platform</span>
      </div>
      <div class="ph-sub">
        DYNAMIC MULTI-OBJECTIVE CVRP &nbsp;·&nbsp;
        INDIA LOGISTICS NETWORK &nbsp;·&nbsp;
        {int(metrics['num_shipments'])} SHIPMENTS &nbsp;·&nbsp;
        {int(metrics['num_vehicles'])} VEHICLES &nbsp;·&nbsp; DEPOT: MUMBAI
      </div>
    </div>
    <div style="display:flex;gap:8px;flex-shrink:0">
      <div class="ph-badge" style="background:rgba(0,212,255,.06);border:1px solid rgba(0,212,255,.15)">
        <div style="font-family:var(--fm);font-size:1.05rem;font-weight:700;color:#00D4FF">−{dp:.1f}%</div>
        <div style="font-family:var(--fm);font-size:.52rem;color:#475569;letter-spacing:.14em;text-transform:uppercase;margin-top:2px">DISTANCE</div>
      </div>
      <div class="ph-badge" style="background:rgba(16,185,129,.06);border:1px solid rgba(16,185,129,.15)">
        <div style="font-family:var(--fm);font-size:1.05rem;font-weight:700;color:#10B981">−{cp:.1f}%</div>
        <div style="font-family:var(--fm);font-size:.52rem;color:#475569;letter-spacing:.14em;text-transform:uppercase;margin-top:2px">COST</div>
      </div>
      <div class="ph-badge" style="background:rgba(139,92,246,.06);border:1px solid rgba(139,92,246,.15)">
        <div style="font-family:var(--fm);font-size:1.05rem;font-weight:700;color:#8B5CF6">−{crp:.1f}%</div>
        <div style="font-family:var(--fm);font-size:.52rem;color:#475569;letter-spacing:.14em;text-transform:uppercase;margin-top:2px">CO₂</div>
      </div>
      <div class="ph-badge" style="background:rgba(245,158,11,.06);border:1px solid rgba(245,158,11,.15)">
        <div style="font-family:var(--fm);font-size:1.05rem;font-weight:700;color:#F59E0B">{metrics['opt_sla_adherence_pct']:.0f}%</div>
        <div style="font-family:var(--fm);font-size:.52rem;color:#475569;letter-spacing:.14em;text-transform:uppercase;margin-top:2px">SLA MET</div>
      </div>
    </div>
  </div>
</div>
""", unsafe_allow_html=True)

# ── KPI Strip ─────────────────────────────────────────────────────────────────
def kpi(col, cls, lbl, val, delta):
    col.markdown(f"""
    <div class="kc {cls}">
        <div class="kc-lbl">{lbl}</div>
        <div class="kc-val">{val}</div>
        <div class="kc-d up">{delta}</div>
    </div>""", unsafe_allow_html=True)

k = st.columns(5)
kpi(k[0],"cy","📏 DISTANCE",      f"{metrics['opt_distance_km']:,.0f} km",   f"▼ {metrics['baseline_distance_km']-metrics['opt_distance_km']:,.0f} km vs baseline")
kpi(k[1],"gr","⏱ TRAVEL TIME",    f"{metrics['opt_time_hr']:.1f} hr",         f"▼ {metrics['baseline_time_hr']-metrics['opt_time_hr']:.1f} hr vs baseline")
kpi(k[2],"am","💰 TOTAL COST",     f"₹{metrics['opt_total_cost']:,.0f}",       f"▼ ₹{metrics['baseline_total_cost']-metrics['opt_total_cost']:,.0f} vs baseline")
kpi(k[3],"vi","🌿 CO₂ EMITTED",   f"{metrics['opt_carbon_kg']:,.0f} kg",      f"▼ {metrics['baseline_carbon_kg']-metrics['opt_carbon_kg']:,.0f} kg vs baseline")
kpi(k[4],"cy","✅ SLA ADHERENCE", f"{metrics['opt_sla_adherence_pct']:.0f}%", f"▲ {metrics['opt_sla_adherence_pct']-metrics['baseline_sla_adherence_pct']:.0f} pts vs baseline")

st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# ROUTE INTELLIGENCE MAP  (original logic — untouched)
# ══════════════════════════════════════════════════════════════════════════════
sec("🗺️", "Route Intelligence Map", "LIVE", "gr")

fig_map = go.Figure()

if show_baseline:
    bl = [DEPOT["latitude"]]  + ships["latitude"].tolist()  + [DEPOT["latitude"]]
    bo = [DEPOT["longitude"]] + ships["longitude"].tolist() + [DEPOT["longitude"]]
    fig_map.add_trace(go.Scattermap(lat=bl, lon=bo, mode="lines",
        line=dict(width=1.5, color="rgba(255,77,77,0.35)"), name="Baseline Route"))

for v in av:
    vdf = routes[(routes["vehicle"]==v) & (routes["priority"].isin(ap))].sort_values("stop_order")
    lats = [DEPOT["latitude"]]  + vdf["latitude"].tolist()  + [DEPOT["latitude"]]
    lons = [DEPOT["longitude"]] + vdf["longitude"].tolist() + [DEPOT["longitude"]]
    col  = VEHICLE_COLORS[(v-1) % len(VEHICLE_COLORS)]
    fig_map.add_trace(go.Scattermap(lat=lats, lon=lons, mode="lines",
        line=dict(width=3, color=col), name=f"Vehicle {v}"))
    for _, row in vdf.iterrows():
        pc = PRIORITY_COLORS.get(row.get("priority","MEDIUM"), "#F59E0B")
        fig_map.add_trace(go.Scattermap(
            lat=[row["latitude"]], lon=[row["longitude"]], mode="markers",
            marker=dict(size=11, color=pc),
            hovertext=(f"<b>{row.get('city',row['shipment_id'])}</b><br>"
                       f"Priority : {row.get('priority','')}<br>"
                       f"Weight   : {row['weight']:.0f} kg<br>"
                       f"Cost     : ₹{row['total_cost']:,.0f}<br>"
                       f"Carbon   : {row['carbon_kg']:.1f} kg CO₂<br>"
                       f"SLA breach: {row['sla_breach_hr']:.1f} hr"),
            hoverinfo="text", showlegend=False))

if show_unassigned:
    assigned = set(routes["shipment_id"])
    ua = ships[~ships["id"].isin(assigned)]
    if not ua.empty:
        fig_map.add_trace(go.Scattermap(lat=ua["latitude"], lon=ua["longitude"], mode="markers",
            marker=dict(size=8, color="#64748B"), name="Unassigned",
            hovertext=ua["city"], hoverinfo="text"))

fig_map.add_trace(go.Scattermap(
    lat=[DEPOT["latitude"]], lon=[DEPOT["longitude"]],
    mode="markers+text", text=["🏭 Mumbai Depot"], textposition="top right",
    marker=dict(size=20, color="#0D1117", symbol="star"), name="Depot"))

fig_map.update_layout(
    map_style="open-street-map",
    map=dict(center=dict(lat=20.5, lon=78.9), zoom=4),
    margin=dict(l=0,r=0,t=0,b=0), height=570,
    paper_bgcolor="rgba(0,0,0,0)",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(6,9,13,0.92)",
                bordercolor="rgba(0,212,255,0.15)", borderwidth=1,
                font=dict(family="'IBM Plex Mono',monospace", color="#94A3B8", size=10)))

st.markdown('<div class="mc">', unsafe_allow_html=True)
st.plotly_chart(fig_map, use_container_width=True)
st.markdown('</div>', unsafe_allow_html=True)
st.caption("🔴 HIGH priority  ·  🟠 MEDIUM priority  ·  🟢 LOW priority  ·  ⭐ Depot (Mumbai)  ·  Use sidebar to filter vehicles & priorities")

st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# ANALYTICS TABS
# ══════════════════════════════════════════════════════════════════════════════
sec("📊", "Analytics & Intelligence")

tab_fleet, tab_cost, tab_expl, tab_sim, tab_ai = st.tabs([
    "🚛  Fleet Analytics",
    "💰  Cost & Carbon",
    "🧠  Explainability",
    "⚡  Disruption Simulator",
    "🤖  AI Assistant",
])


# ────────────────────────────────────────────────────────────────────────────
# TAB 1 — Fleet Analytics
# ────────────────────────────────────────────────────────────────────────────
with tab_fleet:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    box("Compares <b>Baseline</b> (sequential, single-vehicle, distance-only) vs "
        "<b>AI-Optimized</b> multi-vehicle CVRP across all logistics KPIs. "
        "Green deltas = improvement over baseline.")

    def dm(col, label, bv, ov, fmt=",.1f", pre="", suf=""):
        d = ov - bv; pct = d/bv*100 if bv else 0
        col.metric(label, f"{pre}{ov:{fmt}}{suf}",
                   delta=f"{pre}{d:+{fmt}}{suf}  ({pct:+.1f}%)", delta_color="inverse")

    r1 = st.columns(4)
    dm(r1[0],"📏 Distance (km)",    metrics["baseline_distance_km"],  metrics["opt_distance_km"])
    dm(r1[1],"⏱ Travel Time (hr)",  metrics["baseline_time_hr"],      metrics["opt_time_hr"])
    dm(r1[2],"💰 Total Cost (₹)",   metrics["baseline_total_cost"],   metrics["opt_total_cost"], pre="₹")
    dm(r1[3],"🌿 Carbon (kg)",       metrics["baseline_carbon_kg"],    metrics["opt_carbon_kg"])

    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
    r2 = st.columns(4)
    r2[0].metric("⛽ Fuel Saved",   f"₹{metrics['baseline_fuel_cost']-metrics['opt_fuel_cost']:,.0f}",
        delta=f"-{(metrics['baseline_fuel_cost']-metrics['opt_fuel_cost'])/metrics['baseline_fuel_cost']*100:.1f}%", delta_color="inverse")
    r2[1].metric("🛣️ Toll Saved",  f"₹{metrics['baseline_toll_cost']-metrics['opt_toll_cost']:,.0f}",
        delta=f"-{(metrics['baseline_toll_cost']-metrics['opt_toll_cost'])/metrics['baseline_toll_cost']*100:.1f}%", delta_color="inverse")
    r2[2].metric("👷 Driver Saved", f"₹{metrics['baseline_driver_cost']-metrics['opt_driver_cost']:,.0f}",
        delta=f"-{(metrics['baseline_driver_cost']-metrics['opt_driver_cost'])/metrics['baseline_driver_cost']*100:.1f}%", delta_color="inverse")
    r2[3].metric("✅ SLA Adherence",f"{metrics['opt_sla_adherence_pct']:.0f}%",
        delta=f"+{metrics['opt_sla_adherence_pct']-metrics['baseline_sla_adherence_pct']:.0f} pts", delta_color="normal")

    # Utilisation bar
    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
    fig_u = go.Figure(go.Bar(
        x=[f"V{v}" for v in veh_summary["vehicle"]], y=veh_summary["utilization_pct"],
        marker=dict(color=veh_summary["utilization_pct"],
                    colorscale=[[0,"#FF4D4D"],[0.5,"#F59E0B"],[1,"#10B981"]], cmin=0, cmax=100),
        text=veh_summary["utilization_pct"].round(1).astype(str)+"%", textposition="outside",
        textfont=dict(size=10, color="#94A3B8")))
    fig_u.add_hline(y=100, line_dash="dot", line_color="rgba(255,77,77,.35)",
                    annotation_text="Capacity limit", annotation_font=dict(size=9, color="#FF4D4D"),
                    annotation_position="top right")
    chart(fig_u, 230, "VEHICLE CAPACITY UTILISATION (%)")
    fig_u.update_layout(showlegend=False, yaxis_range=[0,115])
    st.plotly_chart(fig_u, use_container_width=True)

    # Vehicle summary table
    st.markdown('<div class="tbl-lbl">PER-VEHICLE SUMMARY</div>', unsafe_allow_html=True)
    dv = veh_summary.copy()
    dv.columns = ["Vehicle","Stops","Load (kg)","Dist (km)","Time (hr)","Fuel ₹","Toll ₹",
                  "Driver ₹","SLA Penalty ₹","Total Cost ₹","Carbon kg","SLA Breaches","Util %"]
    st.dataframe(dv.style.format({
        "Load (kg)":"{:.1f}","Dist (km)":"{:.1f}","Time (hr)":"{:.1f}",
        "Fuel ₹":"₹{:,.0f}","Toll ₹":"₹{:,.0f}","Driver ₹":"₹{:,.0f}",
        "SLA Penalty ₹":"₹{:,.0f}","Total Cost ₹":"₹{:,.0f}",
        "Carbon kg":"{:.1f}","Util %":"{:.1f}%",
    }).background_gradient(subset=["Util %"],cmap="RdYlGn")
      .background_gradient(subset=["SLA Breaches"],cmap="RdYlGn_r"),
    use_container_width=True, hide_index=True)


# ────────────────────────────────────────────────────────────────────────────
# TAB 2 — Cost & Carbon
# ────────────────────────────────────────────────────────────────────────────
with tab_cost:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    c1, c2 = st.columns(2)

    # Cost stacked bar
    with c1:
        fig_cb = go.Figure()
        for cat, bv, ov, col in [
            ("Fuel",   metrics["baseline_fuel_cost"],   metrics["opt_fuel_cost"],   "#00D4FF"),
            ("Toll",   metrics["baseline_toll_cost"],   metrics["opt_toll_cost"],   "#F59E0B"),
            ("Driver", metrics["baseline_driver_cost"], metrics["opt_driver_cost"], "#8B5CF6"),
        ]:
            fig_cb.add_trace(go.Bar(name=cat, x=["Baseline","Optimized"], y=[bv,ov],
                                    marker_color=col, marker_opacity=0.82))
        chart(fig_cb, 300, "COST COMPONENTS: BASELINE vs OPTIMIZED (₹)")
        fig_cb.update_layout(barmode="stack", legend=dict(**PLOTLY_BASE["legend"],orientation="h",y=-0.22))
        st.plotly_chart(fig_cb, use_container_width=True)

    # Savings waterfall
    with c2:
        sv = {"Fuel Saved":   metrics["baseline_fuel_cost"]  -metrics["opt_fuel_cost"],
              "Toll Saved":   metrics["baseline_toll_cost"]  -metrics["opt_toll_cost"],
              "Driver Saved": metrics["baseline_driver_cost"]-metrics["opt_driver_cost"]}
        tot = sum(sv.values())
        fig_wf = go.Figure(go.Waterfall(
            orientation="v", measure=["relative","relative","relative","total"],
            x=list(sv.keys())+["Total Saved"], y=list(sv.values())+[tot],
            connector={"line":{"color":"rgba(148,163,184,.2)"}},
            decreasing={"marker":{"color":"#10B981","opacity":.82}},
            totals={"marker":{"color":"#00D4FF","opacity":.82}},
            text=[f"₹{v:,.0f}" for v in list(sv.values())+[tot]], textposition="outside",
            textfont=dict(size=10,color="#94A3B8")))
        chart(fig_wf, 300, "SAVINGS BREAKDOWN (₹)")
        fig_wf.update_layout(yaxis_title="₹ Saved")
        st.plotly_chart(fig_wf, use_container_width=True)

    # Per-vehicle cost stack
    fig_vc = go.Figure()
    for col, color, label in [("fuel_cost","#00D4FF","Fuel"),("toll_cost","#F59E0B","Toll"),
                               ("driver_cost","#8B5CF6","Driver"),("sla_penalty","#FF4D4D","SLA Penalty")]:
        fig_vc.add_trace(go.Bar(name=label, x=[f"Vehicle {v}" for v in veh_summary["vehicle"]],
                                y=veh_summary[col], marker_color=color, marker_opacity=0.82))
    chart(fig_vc, 250, "PER-VEHICLE COST COMPOSITION (₹)")
    fig_vc.update_layout(barmode="stack", legend=dict(**PLOTLY_BASE["legend"],orientation="h",y=-0.3))
    st.plotly_chart(fig_vc, use_container_width=True)

    # Carbon + SLA
    cc1, cc2 = st.columns(2)
    with cc1:
        co2_s = metrics["baseline_carbon_kg"] - metrics["opt_carbon_kg"]
        fig_co2 = go.Figure(go.Bar(
            x=["Baseline (No AI)","AI Optimized"],
            y=[metrics["baseline_carbon_kg"],metrics["opt_carbon_kg"]],
            marker_color=["#FF4D4D","#10B981"], marker_opacity=0.85,
            text=[f"{metrics['baseline_carbon_kg']:,.1f} kg",f"{metrics['opt_carbon_kg']:,.1f} kg"],
            textposition="outside", textfont=dict(size=10,color="#94A3B8")))
        chart(fig_co2, 250, f"CO₂ EMISSIONS — {co2_s:,.1f} kg SAVED ({co2_s/metrics['baseline_carbon_kg']*100:.1f}% REDUCTION)")
        fig_co2.update_layout(showlegend=False, yaxis_title="kg CO₂")
        st.plotly_chart(fig_co2, use_container_width=True)

        # Carbon per vehicle
        fig_cpv = go.Figure(go.Bar(
            x=[f"V{v}" for v in veh_summary["vehicle"]], y=veh_summary["carbon_kg"],
            marker=dict(color=[VEHICLE_COLORS[i%len(VEHICLE_COLORS)] for i in range(len(veh_summary))], opacity=0.82),
            text=veh_summary["carbon_kg"].round(1).astype(str)+" kg", textposition="outside",
            textfont=dict(size=10,color="#94A3B8")))
        chart(fig_cpv, 210, "CARBON PER VEHICLE (kg CO₂)")
        fig_cpv.update_layout(showlegend=False, yaxis_title="kg CO₂")
        st.plotly_chart(fig_cpv, use_container_width=True)

    with cc2:
        # SLA gauge
        sla_o = metrics["opt_sla_adherence_pct"]; sla_b = metrics["baseline_sla_adherence_pct"]
        fig_g = go.Figure(go.Indicator(
            mode="gauge+number+delta", value=sla_o,
            title={"text":"SLA ADHERENCE — OPTIMIZED","font":{"family":"Barlow Condensed","size":12,"color":"#64748B"}},
            delta={"reference":sla_b,"increasing":{"color":"#10B981"},"suffix":"% vs baseline",
                   "font":{"family":"IBM Plex Mono","size":11}},
            number={"font":{"family":"IBM Plex Mono","size":38,"color":"#E8EEF4"},"suffix":"%"},
            gauge={"axis":{"range":[0,100],"tickfont":{"size":9}},
                   "bar":{"color":"#10B981","thickness":.28},"bgcolor":"rgba(0,0,0,0)",
                   "steps":[{"range":[0,50],"color":"rgba(255,77,77,.12)"},
                             {"range":[50,80],"color":"rgba(245,158,11,.10)"},
                             {"range":[80,100],"color":"rgba(16,185,129,.10)"}],
                   "threshold":{"line":{"color":"#FF4D4D","width":2},"thickness":.75,"value":sla_b}}))
        fig_g.update_layout(height=250,paper_bgcolor="rgba(0,0,0,0)",
                            font=dict(family="IBM Plex Mono",color="#64748B"),margin=dict(l=20,r=20,t=30,b=10))
        st.plotly_chart(fig_g, use_container_width=True)

        # SLA breach heatmap
        bdf = routes[routes["vehicle"].isin(av)].copy()
        bdf["breached"] = (bdf["sla_breach_hr"]>0).astype(int)
        pivot = bdf.groupby(["vehicle","priority"])["breached"].sum().unstack(fill_value=0)
        fig_h = go.Figure(go.Heatmap(
            z=pivot.values, x=pivot.columns.tolist(), y=[f"V{v}" for v in pivot.index],
            colorscale=[[0,"rgba(16,185,129,.2)"],[.5,"rgba(245,158,11,.5)"],[1,"rgba(255,77,77,.8)"]],
            text=pivot.values, texttemplate="%{text}",
            textfont=dict(family="IBM Plex Mono",size=13,color="#E8EEF4"), showscale=False))
        chart(fig_h, 210, "SLA BREACHES: VEHICLE × PRIORITY")
        fig_h.update_layout(xaxis_title="Priority",yaxis_title="Vehicle")
        st.plotly_chart(fig_h, use_container_width=True)

    # Carbon scatter
    fig_sc = px.scatter(routes[routes["vehicle"].isin(av)],
        x="route_distance_km", y="carbon_kg", color="priority", size="weight", hover_name="city",
        color_discrete_map=PRIORITY_COLORS,
        labels={"route_distance_km":"Route Distance (km)","carbon_kg":"Carbon (kg CO₂)"})
    chart(fig_sc, 270, "CARBON EMISSIONS vs ROUTE DISTANCE")
    fig_sc.update_layout(legend=dict(**PLOTLY_BASE["legend"],orientation="h",y=-0.3))
    st.plotly_chart(fig_sc, use_container_width=True)


# ────────────────────────────────────────────────────────────────────────────
# TAB 3 — Explainability
# ────────────────────────────────────────────────────────────────────────────
with tab_expl:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    box("The AI scores each candidate stop across <b>4 objectives simultaneously</b> "
        "(Cost 35% · Time 30% · Carbon 20% · SLA 15%). Charts below reveal which factors "
        "drove decisions — computed via <b>permutation importance</b> (equivalent to SHAP). "
        "No black box: every routing choice is fully traceable.")

    ec1, ec2 = st.columns([1, 2])
    with ec1:
        fig_d = go.Figure(go.Pie(
            labels=["Cost (₹)","Travel Time","Carbon CO₂","SLA Adherence"],
            values=[35, 30, 20, 15], hole=0.62,
            marker=dict(colors=["#00D4FF","#F59E0B","#10B981","#FF4D4D"],
                        line=dict(color="#070B0F",width=2)),
            textinfo="label+percent", textfont=dict(family="IBM Plex Mono",size=10)))
        fig_d.update_layout(height=270, showlegend=False, paper_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#64748B"), margin=dict(l=10,r=10,t=38,b=10),
            annotations=[{"text":"Weights","x":.5,"y":.5,
                "font":{"family":"Barlow Condensed","size":13,"color":"#64748B"},"showarrow":False}],
            title=dict(text="OBJECTIVE WEIGHTS",
                font=dict(family="Barlow Condensed",size=12,color="#94A3B8"),x=0,xref="paper"))
        st.plotly_chart(fig_d, use_container_width=True)

    with ec2:
        fi_l = list(fi.keys()); fi_v = list(fi.values()); mx = max(fi_v)
        fig_fi = go.Figure(go.Bar(
            x=fi_v, y=fi_l, orientation="h",
            marker=dict(color=["#FF4D4D" if v==mx else "#00D4FF" for v in fi_v], opacity=0.82),
            text=[f"{v:.1f}%" for v in fi_v], textposition="outside",
            textfont=dict(size=10,color="#94A3B8")))
        chart(fig_fi, 270, "PERMUTATION-BASED FEATURE IMPORTANCE")
        fig_fi.update_layout(xaxis_title="Importance (%)", yaxis=dict(autorange="reversed",
            gridcolor="rgba(255,255,255,.04)",linecolor="rgba(255,255,255,.07)",tickfont=dict(size=10)))
        st.plotly_chart(fig_fi, use_container_width=True)

    # Per-stop contribution stacked bar
    vf = st.selectbox("Filter by vehicle:",
        ["All Vehicles"]+[f"Vehicle {v}" for v in sorted(routes["vehicle"].unique())], key="expl_vf")
    sc_f = sc if vf == "All Vehicles" else sc[sc["vehicle"]==int(vf.split()[-1])].copy()

    fcs   = ["Travel Time","Fuel Cost","Toll Cost","Driver Cost","Carbon","SLA Breach"]
    fcols = ["#F59E0B","#00D4FF","#8B5CF6","#A78BFA","#10B981","#FF4D4D"]
    fig_st = go.Figure()
    for fc, fc_col in zip(fcs, fcols):
        fig_st.add_trace(go.Bar(name=fc, x=sc_f["city"], y=sc_f[fc],
                                marker_color=fc_col, marker_opacity=0.82))
    chart(fig_st, 340, "PER-STOP SCORE CONTRIBUTION BREAKDOWN")
    fig_st.update_layout(barmode="stack", xaxis_tickangle=-42, yaxis_title="Weighted MO Score",
                         legend=dict(**PLOTLY_BASE["legend"],orientation="h",y=-0.42))
    st.plotly_chart(fig_st, use_container_width=True)

    # Hardest stops table
    st.markdown('<div class="tbl-lbl">HARDEST-TO-SCHEDULE STOPS (TOP 10)</div>', unsafe_allow_html=True)
    box("Stops with the <b>highest multi-objective score</b> — driven by long distance, "
        "heavy traffic, tight SLA windows, high carbon factors, or heavy payload combinations.")
    ts = routes.nlargest(10,"mo_score")[["city","vehicle","priority","weight",
        "travel_time_hr","fuel_cost","toll_cost","carbon_kg","sla_breach_hr","mo_score"]].reset_index(drop=True)
    st.dataframe(ts.style.format({
        "travel_time_hr":"{:.2f} hr","fuel_cost":"₹{:.0f}","toll_cost":"₹{:.0f}",
        "carbon_kg":"{:.2f} kg","sla_breach_hr":"{:.1f} hr","mo_score":"{:.4f}","weight":"{:.0f} kg",
    }).background_gradient(subset=["mo_score"],cmap="YlOrRd"),
    use_container_width=True, hide_index=True)


# ────────────────────────────────────────────────────────────────────────────
# TAB 4 — Disruption Simulator
# ────────────────────────────────────────────────────────────────────────────
with tab_sim:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    box("Use the <b>Simulation Controls</b> in the left sidebar to trigger a disruption. "
        "The AI re-plans affected vehicle routes in real time — demonstrating dynamic "
        "CVRP re-optimization as used in production fleet management systems.")

    # Risk monitor
    risk = ships[["city","traffic_mult","priority","sla_hours"]].copy()
    risk["risk"] = (risk["traffic_mult"]/1.8*0.6 +
                    risk["sla_hours"].map({24:1.0,48:.5,72:.2})*0.4).round(3)
    risk["status"] = risk["risk"].apply(lambda x: "HIGH RISK" if x>.7 else ("MONITOR" if x>.4 else "STABLE"))
    risk = risk.sort_values("risk",ascending=False)

    fig_r = px.bar(risk.head(15), x="city", y="risk", color="status",
        color_discrete_map={"HIGH RISK":"#FF4D4D","MONITOR":"#F59E0B","STABLE":"#10B981"},
        labels={"risk":"Risk Score","city":"City"})
    fig_r.add_hline(y=0.7, line_dash="dot", line_color="rgba(255,77,77,.5)",
                    annotation_text="Re-optimize threshold",
                    annotation_font=dict(size=9,color="#FF4D4D"), annotation_position="top left")
    chart(fig_r, 290, "TOP 15 CITIES — RE-OPTIMIZATION RISK MONITOR")
    fig_r.update_layout(xaxis_title="", yaxis_title="Risk Score",
                        legend=dict(**PLOTLY_BASE["legend"],orientation="h",y=-0.3))
    st.plotly_chart(fig_r, use_container_width=True)

    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)

    # Simulation result
    if not st.session_state.get("sim_r"):
        st.markdown("""<div class="si">
            <div class="si-i">⚡</div>
            <div class="si-t">No Active Simulation</div>
            <div class="si-s">Select a disruption type in the sidebar and press Trigger.</div>
        </div>""", unsafe_allow_html=True)
    else:
        stype, res = st.session_state["sim_r"]

        if stype == "traffic":
            if res.get("triggered"):
                box(f"<b>🚦 Traffic Disruption — {res['city']}</b><br>"
                    f"Traffic: {res['orig_mult']:.2f}× → <b style='color:#FF4D4D'>{res['new_mult']:.2f}×</b> "
                    f"· Travel time +{res['pct']:.1f}% (30% threshold breached)<br>"
                    f"<b>⚠️ Re-optimization triggered for Vehicle {res['vid']}</b>", "w")
                box(f"✅ <b>Vehicle {res['vid']} re-routed.</b> "
                    f"{res['city']} moved to last stop — all other deliveries protected.", "o")
                mc = st.columns(3)
                mc[0].metric("Original Route",    f"{res['od']:.1f} km")
                mc[1].metric("Re-Optimized Route",f"{res['nd']:.1f} km",
                             delta=f"{res['nd']-res['od']:+.1f} km", delta_color="inverse")
                mc[2].metric("Traffic Level",     f"{res['new_mult']:.1f}×",
                             delta=f"+{res['new_mult']-res['orig_mult']:.1f}×")
                d1, d2 = st.columns(2)
                with d1:
                    st.markdown('<div class="tbl-lbl" style="color:#64748B">ORIGINAL STOP ORDER</div>', unsafe_allow_html=True)
                    st.dataframe(res["orig"][["city","priority","weight","sla_hours"]].reset_index(drop=True),
                                 use_container_width=True, hide_index=True, height=200)
                with d2:
                    st.markdown('<div class="tbl-lbl" style="color:#10B981">RE-OPTIMIZED STOP ORDER</div>', unsafe_allow_html=True)
                    st.dataframe(res["reopt"][["city","priority","weight","sla_hours"]].reset_index(drop=True),
                                 use_container_width=True, hide_index=True, height=200)
            else:
                box(f"✅ Traffic {res['new_mult']:.1f}× — only +{res['pct']:.1f}% increase (< 30% threshold). No re-routing needed.", "o")

        elif stype == "esc":
            if res.get("already"):
                box(f"✅ <b>{res['city']}</b> is already HIGH priority — no action needed.", "o")
            else:
                box(f"✅ <b>{res['city']}</b> escalated: "
                    f"<b style='color:#F59E0B'>{res['op']}</b> → <b style='color:#FF4D4D'>HIGH</b><br>"
                    f"Moved to stop #1 on Vehicle {res['vid']}. SLA: {res['os']}h → 24h.", "o")
                box(f"<b>Re-Optimization Actions:</b><br>"
                    f"• Priority: {res['op']} → HIGH<br>"
                    f"• SLA tightened: {res['os']}h → 24h<br>"
                    f"• {res['city']} inserted at stop #1 of Vehicle {res['vid']}<br>"
                    f"• Estimated time: {res['ot']:.1f} hr → "
                    f"<b style='color:#10B981'>{res['nt']:.1f} hr</b> (−{res['ot']-res['nt']:.1f} hr)", "w")
                mc = st.columns(3)
                mc[0].metric("Old SLA Window", f"{res['os']}h")
                mc[1].metric("New SLA Window", "24h", delta="Tightened to urgent")
                mc[2].metric("Time Saved", f"{res['ot']-res['nt']:.1f} hr",
                             delta=f"-{res['ot']-res['nt']:.1f} hr", delta_color="inverse")
                d1, d2 = st.columns(2)
                with d1:
                    st.markdown('<div class="tbl-lbl" style="color:#64748B">ORIGINAL STOP ORDER</div>', unsafe_allow_html=True)
                    st.dataframe(res["orig"][["city","priority","weight","sla_hours"]].reset_index(drop=True),
                                 use_container_width=True, hide_index=True, height=200)
                with d2:
                    st.markdown('<div class="tbl-lbl" style="color:#10B981">RE-OPTIMIZED STOP ORDER</div>', unsafe_allow_html=True)
                    st.dataframe(res["new"][["city","priority","weight","sla_hours"]].reset_index(drop=True),
                                 use_container_width=True, hide_index=True, height=200)


# ────────────────────────────────────────────────────────────────────────────
# TAB 5 — AI Assistant (RAG Chatbot) — calls rag_chatbot.py
# ────────────────────────────────────────────────────────────────────────────
with tab_ai:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    box("<b>LoRRI Copilot</b> is a RAG-powered AI assistant with full access to this "
        "optimization run's live data: routes, costs, vehicles, carbon, and SLA metrics. "
        "Every answer is grounded in real numbers — not hallucinated.")

    # Import chatbot
    try:
        from rag_chatbot import render_chatbot
        render_chatbot(rag)
    except ImportError:
        st.error("rag_chatbot.py not found. Please ensure it is in the same directory.")


# ══════════════════════════════════════════════════════════════════════════════
# FOOTER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("""
<div class="footer">
    LoRRI &nbsp;·&nbsp; AI Route Intelligence Platform &nbsp;·&nbsp;
    Dynamic Multi-Objective CVRP &nbsp;·&nbsp; Streamlit + Plotly &nbsp;·&nbsp;
    Permutation-Based Explainability &nbsp;·&nbsp; RAG AI Assistant
</div>
""", unsafe_allow_html=True)
