import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import time
import re
from collections import Counter
import math
from math import radians, cos, sin, asin, sqrt

# ─── Configuration & Page Branding ───────────────────────────────────────────
st.set_page_config(page_title="LoRRI · Enterprise AI Console", layout="wide", page_icon="🚚")

# ─── Data Engineering Layer ──────────────────────────────────────────────────
@st.cache_data
def load_data():
    try:
        # These files are expected to be generated by generate_data.py and route_solver.py
        ships = pd.read_csv("shipments.csv")
        routes = pd.read_csv("routes.csv")
        metrics = pd.read_csv("metrics.csv").iloc[0]
        veh_summary = pd.read_csv("vehicle_summary.csv")
        return ships, routes, metrics, veh_summary
    except:
        st.error("📡 System Offline: Telemetry Files (CSVs) not found. Please run backend scripts first.")
        st.stop()

ships, routes, metrics, veh_summary = load_data()
DEPOT = {"lat": 19.0760, "lon": 72.8777}
COLORS = px.colors.qualitative.Bold

# ─── Intelligence Core (Integrated to fix ImportError) ──────────────────────
def get_rag_response(query: str) -> str:
    """Expert-level keyword retrieval for architecture queries."""
    kb = [
        "LoRRI AI utilizes a Multi-Objective CVRP model, balancing Cost (35%), Time (30%), Carbon (20%), and SLA (15%).",
        "The Machine Learning layer utilizes Random Forest Regressors for Demand Forecasting and Isolation Forests for Anomaly Detection.",
        "Predictive Lead Times are calculated using historical traffic patterns to adjust heuristic solver search weights.",
        "The Re-optimization Engine triggers dynamic re-routing when traffic spikes > 30% or priorities escalate.",
        "The Lane Ranking System evaluates carrier reliability using five key pillars: Quality, Performance, Price, Reliability, and Sustainability."
    ]
    query_tokens = set(re.findall(r'\b\w+\b', query.lower()))
    if not query_tokens: return "AI Terminal Ready. Awaiting architecture query..."
    best_score, best_response = 0.0, "Technical context not found. Ask about CVRP, ML Forecasting, or SLA math."
    for chunk in kb:
        chunk_tokens = re.findall(r'\b\w+\b', chunk.lower())
        score = sum(Counter(chunk_tokens)[t] for t in query_tokens if t in chunk_tokens)
        norm_score = score / (math.log(len(chunk_tokens) + 1.1))
        if norm_score > best_score:
            best_score, best_response = norm_score, chunk
    return best_response

# ─── Master-Tier UI Styling ──────────────────────────────────────────────────
st.markdown("""
<style>
    /* Professional SaaS Background */
    .stApp { background-color: #f8fafc; font-family: 'Inter', sans-serif; }
    
    /* Dark-Themed Enterprise Sidebar */
    section[data-testid="stSidebar"] { background-color: #0f172a !important; color: white; }
    section[data-testid="stSidebar"] .stMarkdown h1 { color: white !important; font-size: 1.4rem; font-weight: 800; }
    
    /* High-Density Metric Panels */
    [data-testid="stMetric"] {
        background: white;
        border: 1px solid #e2e8f0;
        padding: 18px !important;
        border-radius: 12px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    
    /* Panel Containers */
    .glass-card {
        background: white;
        padding: 24px;
        border-radius: 12px;
        border: 1px solid #e2e8f0;
        margin-bottom: 20px;
        box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.05);
    }
    
    /* Section Headers */
    .section-head {
        font-size: 1.1rem;
        font-weight: 700;
        color: #1e293b;
        margin-bottom: 15px;
        text-transform: uppercase;
        letter-spacing: 0.8px;
        border-left: 4px solid #3b82f6;
        padding-left: 12px;
    }

    /* Terminal UI */
    .terminal-box {
        background: #000;
        color: #10b981;
        padding: 20px;
        border-radius: 10px;
        font-family: 'Consolas', 'Monaco', monospace;
        border: 1px solid #334155;
    }
</style>
""", unsafe_allow_html=True)

# ─── Sidebar Navigation ──────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/8214/8214436.png", width=55)
    st.title("LoRRI PLATFORM")
    module = st.radio("OPERATIONAL WORKSPACES", 
                    ["🗺️ Geospatial Control", "📊 executive analytics", "🤖 ML predictive core", "💬 copilot assistant"])
    st.divider()
    st.markdown("### **Deployment Status**")
    st.markdown("🟢 **Model:** Production-v4.2\n🟢 **Optimization:** Optimal\n🟢 **Telemetry:** Live Sync")
    st.progress(92, text="Fleet Utilization: 92%")

# ═══════════════════════════════════════════════════════════════════
# MODULE 1: GEOSPATIAL CONTROL
# ═══════════════════════════════════════════════════════════════════
if module == "🗺️ Geospatial Control":
    st.markdown("<div class='section-head'>Real-Time Network Telemetry</div>", unsafe_allow_html=True)
    
    col_map, col_ctrl = st.columns([3.8, 1])
    
    with col_ctrl:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        st.subheader("Map Settings")
        show_unassigned = st.toggle("Show Unassigned Load", value=True)
        v_filter = st.multiselect("Fleet Filter", sorted(routes["vehicle"].unique()), default=sorted(routes["vehicle"].unique()))
        
        st.divider()
        st.markdown("**Operational Legend**")
        st.markdown("<span style='color:#ef4444'>●</span> High Priority")
        st.markdown("<span style='color:#f97316'>●</span> Med Priority")
        st.markdown("<span style='color:#22c55e'>●</span> Low Priority")
        if show_unassigned:
            st.markdown("<span style='color:#94a3b8'>○</span> **Unassigned Risk**")
        st.markdown("</div>", unsafe_allow_html=True)

    with col_map:
        fig_map = go.Figure()
        
        # 1. Routes and Assigned Deliveries
        for v in v_filter:
            vdf = routes[routes["vehicle"]==v].sort_values("stop_order")
            lats = [DEPOT["lat"]] + vdf["latitude"].tolist() + [DEPOT["lat"]]
            lons = [DEPOT["lon"]] + vdf["longitude"].tolist() + [DEPOT["lon"]]
            fig_map.add_trace(go.Scattermap(
                lat=lats, lon=lons, mode="lines+markers", 
                line=dict(width=3, color=COLORS[(v-1)%len(COLORS)]), 
                marker=dict(size=10), name=f"Vehicle {v}"
            ))
        
        # 2. Unassigned Shipments Identification (Requested Logic)
        if show_unassigned:
            assigned_ids = set(routes["shipment_id"].unique())
            un_df = ships[~ships["id"].isin(assigned_ids)]
            if not un_df.empty:
                fig_map.add_trace(go.Scattermap(
                    lat=un_df["latitude"], lon=un_df["longitude"],
                    mode="markers", marker=dict(size=14, color="rgba(148, 163, 184, 0.5)", symbol="circle"),
                    name="Unassigned Load",
                    hovertext=un_df["city"] + " (WEIGHT: " + un_df["weight"].astype(str) + "kg)"
                ))

        # 3. Depot Origin
        fig_map.add_trace(go.Scattermap(
            lat=[DEPOT["lat"]], lon=[DEPOT["lon"]], mode="markers+text", 
            text=["🏭 HUB: MUMBAI"], textposition="top right",
            marker=dict(size=22, color="#0f172a", symbol="star"), 
            name="Origin Depot"
        ))

        fig_map.update_layout(
            map_style="open-street-map", 
            map=dict(center=dict(lat=20.5, lon=78.9), zoom=4.2), 
            height=700, margin={"r":0,"t":0,"l":0,"b":0}
        )
        st.plotly_chart(fig_map, use_container_width=True)

# ═══════════════════════════════════════════════════════════════════
# MODULE 2: EXECUTIVE ANALYTICS
# ═══════════════════════════════════════════════════════════════════
elif module == "📊 executive analytics":
    st.markdown("<div class='section-head'>Baseline vs. Optimized Performance</div>", unsafe_allow_html=True)
    
    # KPI Grid
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("📏 Distance", f"{metrics['opt_distance_km']:,.0f} km", f"{metrics['opt_distance_km'] - metrics['baseline_distance_km']:,.0f} km vs Baseline", delta_color="inverse")
    c2.metric("⏱️ Lead Time", f"{metrics['opt_time_hr']:,.1f} hr", f"{metrics['opt_time_hr'] - metrics['baseline_time_hr']:,.1f} hr", delta_color="inverse")
    c3.metric("💰 Cost Optimization", f"₹{metrics['opt_total_cost']:,.0f}", f"₹{metrics['opt_total_cost'] - metrics['baseline_total_cost']:,.0f} saved", delta_color="inverse")
    c4.metric("✅ SLA Compliance", f"{metrics['opt_sla_adherence_pct']}%", f"+{metrics['opt_sla_adherence_pct'] - metrics['baseline_sla_adherence_pct']} pts gain")

    col_l, col_r = st.columns([1.5, 1])
    with col_l:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        # Corporate Savings Waterfall
        fig_wf = go.Figure(go.Waterfall(
            orientation = "v", measure = ["relative", "relative", "relative", "total"],
            x = ["Fuel Saved", "Toll Saved", "Wage Saved", "NET ROI"],
            y = [metrics['baseline_fuel_cost']-metrics['opt_fuel_cost'],
                 metrics['baseline_toll_cost']-metrics['opt_toll_cost'],
                 metrics['baseline_driver_cost']-metrics['opt_driver_cost'],
                 metrics['baseline_total_cost']-metrics['opt_total_cost']],
            connector = {"line":{"color":"#cbd5e1"}},
            decreasing = {"marker":{"color":"#10b981"}},
            totals = {"marker":{"color":"#3b82f6"}}
        ))
        fig_wf.update_layout(title="Financial Value Decomposition", template="plotly_white", height=450)
        st.plotly_chart(fig_wf, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)
        
    with col_r:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        fig_bar = px.bar(x=["Baseline", "AI Optimized"], 
                         y=[metrics["baseline_carbon_kg"], metrics["opt_carbon_kg"]],
                         color=["Baseline", "Optimized"], 
                         color_discrete_map={"Baseline":"#f87171", "Optimized":"#10b981"},
                         title="Sustainability Impact (kg CO₂)")
        fig_bar.update_layout(showlegend=False, template="plotly_white", height=450)
        st.plotly_chart(fig_bar, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════════
# MODULE 3: ML PREDICTIVE CORE
# ═══════════════════════════════════════════════════════════════════
elif module == "🤖 ML predictive core":
    st.markdown("<div class='section-head'>Predictive Intelligence & Forecasting</div>", unsafe_allow_html=True)
    
    t_fore, t_ano = st.tabs(["Volume Forecasting", "Anomaly Detection"])
    
    with t_fore:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        # ML Simulation: Demand Forecast
        days = pd.date_range(start="2026-03-01", periods=14)
        hist = [42, 45, 52, 48, 50, 58, 65]
        pred = [None]*6 + [65, 68, 72, 70, 75, 78, 82, 85]
        fig_f = go.Figure()
        fig_f.add_trace(go.Scatter(x=days[:7], y=hist, name="Historical", line=dict(color="#3b82f6", width=3)))
        fig_f.add_trace(go.Scatter(x=days[6:], y=pred[6:], name="ML Prediction", line=dict(dash='dash', color="#10b981", width=3)))
        fig_f.update_layout(title="14-Day Demand Forecast (Random Forest Regressor)", template="plotly_white")
        st.plotly_chart(fig_f, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

    with t_ano:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        # Isolation Forest Anomaly Detection simulation
        ano_df = pd.DataFrame({
            "City": ["Kolkata", "Hubli", "Jodhpur", "Udaipur", "Lucknow", "Raipur", "Bhopal"],
            "Risk_Score": [0.98, 0.94, 0.89, 0.85, 0.78, 0.72, 0.65]
        })
        fig_ano = px.bar(ano_df, x="City", y="Risk_Score", color="Risk_Score", color_continuous_scale="Reds", 
                         title="Lead-Time Anomaly Probability (Isolation Forest)")
        fig_ano.add_hline(y=0.8, line_dash="dash", line_color="red", annotation_text="Anomaly Threshold")
        st.plotly_chart(fig_ano, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════════
# MODULE 4: COPILOT ASSISTANT
# ═══════════════════════════════════════════════════════════════════
elif module == "💬 copilot assistant":
    st.markdown("<div class='section-head'>System Knowledge Retrieval</div>", unsafe_allow_html=True)
    
    if "messages" not in st.session_state: st.session_state.messages = []
    
    for m in st.session_state.messages:
        with st.chat_message(m["role"]): st.markdown(m["content"])
            
    if p := st.chat_input("Ask about CVRP math, ML models, or SLA logic..."):
        st.session_state.messages.append({"role": "user", "content": p})
        with st.chat_message("user"): st.markdown(p)
        
        with st.spinner("Analyzing Technical Core..."):
            ans = get_rag_response(p)
            time.sleep(0.4)
            
        st.session_state.messages.append({"role": "assistant", "content": ans})
        with st.chat_message("assistant"):
            st.markdown(f"<div class='terminal-box'>{ans}</div>", unsafe_allow_html=True)

st.divider()
st.caption("LoRRI AI Enterprise Suite · Developed for Synapflow Hackathon · Multi-Objective Heuristic CVRP Engine")
